version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 590183911139.dkr.ecr.us-east-1.amazonaws.com/repo1-nginx
      - envsubst < ecs/task-definition.json > ecs/task-definition1.json
      - mkdir ~/abc
      - cd ~/abc
      # - mkdir pgw
      # - mkdir merchant
      # - mkdir backoffice
      # - mkdir agent
      # - mkdir partner
      - |
          cat > ~/Dockerfile << EOF
          FROM 590183911139.dkr.ecr.us-east-1.amazonaws.com/repo1-nginx:latest
          WORKDIR .
          COPY ./abc/ .
          EXPOSE 8080
          # CMD [ "npm", "run", "start" ]
          EOF
      - cat ~/Dockerfile
  build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        # - npm install
        # - npm run build
        - ls
        - docker build -t repo1-nginx .
  post_build:
    commands:
        - docker tag repo1-nginx:latest 590183911139.dkr.ecr.us-east-1.amazonaws.com/repo1-nginx:latest
        - echo repose-ecs
        - docker push 590183911139.dkr.ecr.us-east-1.amazonaws.com/repo1-nginx:latest
        - aws ecs register-task-definition --family taskBackend --region us-east-1 --cli-input-json file:///$CODEBUILD_SRC_DIR/ecs/task-definition1.json
        - TASK_REVISION=$(aws ecs describe-task-definition --task-definition taskBackend --region us-east-1)
        - aws ecs update-service --cluster Backend-cluster --service Backendservice --region us-east-1 --task-definition taskBackend
